### PR TITLE
Support referencing AWS KMS keys by aliases

### PR DESCRIPTION
**Pull request by darend**
## what

Allow KMS keys to be referenced by alias instead of the complete ARN

Example use:
```
creation_rules:
        - kms: "arn:aws:kms:us-west-2:1234567890:alias/my-sops-key,
                arn:aws:kms:us-east-1:1234567890:key/ba2dad9b-032f-42bd-aa69-6dd4012931f4"
```

## why

Addresses issue https://github.com/mozilla/sops/issues/381

## testing

Unit tests are passing, its not clear how to run the functional tests

### CODE REVIEW

**Comment by prageethw** [comment]
is https://github.com/mozilla/sops/issues/381 fully addressed in this PR?  which release it is included?

**Comment by prageethw** [comment]
Hi @autrilla,
Is there any plans to get this feature released asap, I'm eagerly waiting as this let me to automatic rollover of keys :), Happy to test my self if you give me a release #

**Comment by autrilla** [comment]
There are a few PRs I'd like to get merged before cutting a release. I'll see if I can expedite that :)

**Comment by prageethw** [comment]
> There are a few PRs I'd like to get merged before cutting a release. I'll see if I can expedite that :)

thanks, Mate...

**Pull request closed without merging**
